### ISSUE TITLE
Question Regarding use of mixin

### ISSUE THREAD

**Issue by chasak** [manakuro/golang-clean-architecture-ent-gqlgen#2]
I found your article about [Clean Architecture](https://betterprogramming.pub/clean-architecture-with-ent-and-gqlgen-a789933a3665). I found it insightful.
I am new to using ENT. Your use of mixin is quite interesting. 

```
// UserMixin defines Fields
type UserMixin struct {
	entMixin.Schema
}

// Fields of the User.
func (UserMixin) Fields() []ent.Field {
...
```

instead of defining fields of `user` struct you defined them on `UserMixin` struct. Why?
I am sorry for adding this as an issue.
Thanks

**Comment by manakuro** [comment]
@chasak 
I use Mixin to join the fields because I want to order the columns in the database. In this case, the columns are ordered as follows.

```
id
name
age
created_at
updated_at
```

https://github.com/manakuro/golang-clean-architecture-ent-gqlgen/blob/c491ccdb0dc59c3c221fc331ffe75796eae158e3/ent/schema/user.go#L42-L48

**Comment by chasak** [comment]
Thanks for your answer
